# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yuyang Zhang
title: Master student at Peking University, China
email: yuyangzhang@stu.pku.edu.cn
website: YuyangZhang777.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links

# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm currently a third year master student in Peking University,
  specializing in robotics. I work in Meng's lab, led by Assistant Professor Meng Guo. 
  
  My research work includes multi-robot systems, human-robot collaboration and task and motion planning for robots.
  I have published two papers in top conferences(**CDC** and **RSS**), and my third paper is currently under review at **ICRA**. 
  I have worked on many robotics projects and am familiar with <mark>ROS</mark>.
  I have designed and developed many algorithms and carried out a lot of simulation and real robots experiments on <mark>UGVs</mark> and <mark>UAVs</mark>.
 # I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Peking University
        caption: Sep 2022 - Current
        sub_title: Master's Degree, Robotics
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I'm currently a third year master student at College of Engineering, Peking University, China,
          specializing in robotics in the Department of Mechanical Engineering. I will graduate in June 2025. 
          During the two and a half year, I have worked on many robotics projects and papers, 
          designed and developed many algorithms and accumulated a plenty of experiment experience both in simulation and real robots.
      - layout: left
        title: Zhejiang Sci-Tech University
        caption: Sep 2014 - Jun 2018
        sub_title: Bachelor's Degree, Digital media technology
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I studied in ZSTU and majored in digital media technology. It's a interdisciplinary major that includes computer science and art design. 
          After four years study, I become both a programmer and a designer. 
          I mastered many Adobe softwares such as Illustrator, Photoshop, Premier and so on, which I believe are essential skills for academic paper writing.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Papers
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - ### **Yuyang Zhang\***, Zhuoli Tian\*, Jinsheng Wei, Meng Guo. FlyKites: Human-centric Interactive 
          Exploration and Assistance under Limited Communication. IEEE International Conference on Robotics
            and Automation (**ICRA**), Atlanta, USA, 2025. (**Under review**)

          ![img](/images/icra.png )

          *This work presents a human-centric interactive exploration and assistance framework under limited communication. 
          Robots can switch between exploration mode and assistance mode. 
          Robots in assistance mode can form a communication chain, enabling human operator to assist 
          and interact with robots in various multimedia ways, such as video transmission and remote control.*

          -  Zhuoli Tian, **Yuyang Zhang**, Jinsheng Wei, Meng Guo. iHERO: Interactive Human-oriented Explo
            ration and Supervision Under Scarce Communication. Robotics: Science and Systems (**RSS**), Delft,
            Netherlands, 2024.

          ![img](/images/rss.png )

          *This work proposes an interactive human-oriented online coordination framework for
          collaborative exploration and supervision under scarce communication. The human operator 
          can get updated data in time, prioritize certain region and move within the explored area.*

          - **Yuyang Zhang**, Meng Guo. Online Planning of Uncertain MDPs under Temporal Tasks and Safe
            Return Constraints. IEEE Conference on Decision and Control (**CDC**), Cancun, Mexico, 2022.

          ![img](/images/cdc.png )

          *This work addresses the online motion planning problem of mobile robots under complex high-level tasks.
          The robot motion is modeled as an uncertain Markov Decision Process while the tasks are specified as LTL formulas.*
          The proposed framework enabling the robot to explore and update in a Bayesian way and a safe-return requirement is enforced.

      - layout: top-middle
        title: Patent
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          -  Meng Guo, **Yuyang Zhang**, Zhuoli Tian, Jinsheng Wei. System, method and device for multi-robot
            collaborative exploration, Patent, ZL 2024 1 0642067.9, 2024.08.09.


      - layout: top-middle
        title: Thesis
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          - **YuyangZhang**, YaoJin. Development of an AR-based Sketch-style Ceramic Modeling System. Bachelor Thesis,
            Zhejiang Sci-Tech University, 2018. ("One hundred Outstanding Bachelor's Theses"
            award of Zhejiang Sci-Tech University)

          <img src="/images/bachelor.png" width="50%"/>

          *I developed an Android application to recognize the semantic information from a user's sketch and generate a 3D ceramic model 
          to assist the ceramic design.*
      
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
